In [1]:
import os
os.chdir("../../../..")
from src.midterm import AtlasCountyParser

# Module Usage
## Atlas County Parser
This is essentially the only object that needs to be directly created. The other objects can be accessed through this wrapper object.

In [2]:
# Default values will load cached data from module files
parser = AtlasCountyParser()

In [3]:
# The county-level dataframe is accessed through the dataFrame prop
parser.dataFrame.head()

,LACCESS_POP10,LACCESS_POP15,PCH_LACCESS_POP_10_15,PCT_LACCESS_POP10,PCT_LACCESS_POP15,LACCESS_LOWI10,LACCESS_LOWI15,PCH_LACCESS_LOWI_10_15,PCT_LACCESS_LOWI10,PCT_LACCESS_LOWI15,...,PCT_NHPI10,PCT_65OLDER10,PCT_18YOUNGER10,MEDHHINC15,POVRATE15,PERPOV10,CHILDPOVRATE15,PERCHLDPOV10,METRO13,POPLOSS10
36103,453547.724578,380951.607555,-16.006280,30.371160,25.509868,62976.169009,58308.524326,-7.411763,4.217107,3.904545,...,0.018415,13.512773,23.950849,87634.0,7.8,0.0,10.7,0.0,1.0,0.0
36061,2.000000,2.000000,0.000000,0.000126,0.000126,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.033609,13.503793,14.782710,75136.0,17.6,0.0,24.9,1.0,1.0,0.0
36085,22938.268406,4248.678501,-81.477771,4.893706,0.906423,5810.399714,806.547375,-86.118900,1.239605,0.172071,...,0.029228,12.660594,23.297207,71058.0,14.2,0.0,18.3,0.0,1.0,0.0
36005,12461.685079,7135.332473,-42.741833,0.899690,0.515146,846.616493,12.741068,-98.495060,0.061123,0.000920,...,0.028734,10.532175,26.582476,35102.0,30.3,1.0,42.6,1.0,1.0,0.0
36119,142030.083025,140483.706796,-1.088767,14.964507,14.801579,12044.982499,13090.026891,8.676180,1.269078,1.379185,...,0.022969,14.658107,24.022429,85688.0,10.1,0.0,13.1,0.0,1.0,0.0

In [4]:
# To define the column headers, use the data_dictionary
parser.data_dictionary.get_variable_properties(
    'PCH_LACCESS_POP_10_15')

{'Category Name': 'Access and Proximity to Grocery Store',
 'Category Code': 'ACCESS',
 'Subcategory Name': 'Overall',
 'Variable Name': 'Population, low access to store (% change), 2010 -15',
 'Variable Code': 'PCH_LACCESS_POP_10_15',
 'Geography': 'CNTY10',
 'Units': '% change'}

In [5]:
# To lookup a FIPS code metadata, use fips_reference
parser.fips_reference.head()

,Zip Code,State Name,State Abrv,State Code,County Name,County Code,FIPS Code,ANSI Code,Centroid Lat,Centroid Long
0,501,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218
1,544,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218
2,6390,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218
3,11701,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218
4,11702,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218